### ISSUE TITLE
Unable to load in-cluster configuration

### ISSUE THREAD

**Issue by ErwinRussel** [DiegoStock12/kubeml#2]
Hi @DiegoStock12,

After installing KubeML and all the other stuff (fission etc.), I wanted to create a function. 
However when I run:

`./kubeml function create --name example --code network.py`

I get the following error:

`Error: could not create fission client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`

I tried googling around to find how to find and set these variables, but no luck so far. Is this something I forgot to set during the installation process?

Many thanks

**Comment by DiegoStock12** [comment]
Hi Erwin! 

Well I think this is because to access the cluster the client needs to read the Kubernetes config to find the IP and so on. What it basically does is look for the KUBECONFIG environment variable.

This should be pointing towards thhe file that normally is under ~/.kube/config

This should solve the issue, but if you have more let me know!

**Comment by ErwinRussel** [comment]
Thanks Diego!

It was indeed just as simple as the command

`export KUBECONFIG=~/.kube/config`

Thanks for stating the obvious!!
